config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  # Log in / Log out
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # Sign up
  get 'signup', to: 'users#new'
  
  # Users
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :favouriteposts
    end
  end
  
  # Posts
  resources :microposts, only: [:create, :destroy]
  
  # Follows
  resources :relationships, only: [:create, :destroy]
  
  # Favourites
  resources :favourites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :micropost, class_name: 'Micropost'
  
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
end 

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, 
                    uniqueness: { case_sensitive: false }
  has_secure_password

  # 投稿機能
  has_many :microposts
  
  # follow 機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  # favourite 機能
  has_many :favourites
  has_many :favouriteposts, through: :favourites, source: :micropost
  
  # follow 機能
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  # favourite 機能
  def favourite(micropost)
    Favourite.find_or_create_by(user_id: self.id, micropost_id: micropost.id)
  end
  
  def unfavourite(micropost)
    favourite = self.favourites.find_by(micropost_id: micropost.id)
    favourite.destroy if favourite
  end
  
  def favourite?(micropost)
    self.favouriteposts.include?(micropost)
  end
  
  # timeline 機能
  def feed_microposts
    Micropost.where(user_id: self.following_ids + [self.id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_microposts = user.microposts.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_favourites = user.favourites.count
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @micropost = Micropost.find(params[:micropost_id])
    current_user.favourite(@micropost)
    flash[:success] = 'Favourite!'
    redirect_to root_path
  end

  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    current_user.unfavourite(@micropost)
    flash[:success] = 'Unfavourite!'
    redirect_to root_path
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to root_url
    else
      @microposts = current_user.feed_microposts.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = 'メッセ―ジを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def micropost_params
    params.require(:micropost).permit(:content)
  end
  
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
      redirect_to root_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_path
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @micropost = current_user.microposts.build #form_for 用
      @microposts = current_user.feed_microposts.order('created_at DESC').page(params[:page])
      @favouriteposts = current_user.favouriteposts.order('created_at DESC').page(params[:page])
      counts(@user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers]

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @micropost = current_user.microposts.build
    @microposts = @user.microposts.order('created_at DESC').page(params[:page])
    @favourites = current_user.favourites.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def favourites
    @micropost = current_uesr.microposts.build
    @uesr = User.find(params[:id])
    @microposts = @uesr.microposts.order('created_at DESC').page(params[:page])
    @favourites = current_user.favourites.order('created_at DESC').page(params[:page])
  end
  
    
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/favourites/_favourite_button.html.erb
<% if current_user.favourite?(micropost) %>
  <%= form_for(current_user.favourites.find_by(micropost_id: micropost.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :micropost_id, micropost.id %>
    <%= f.submit 'Unfavourite', class: 'btn btn-danger btn-xs' %>
  <% end %>
<% else %>
  <%= form_for(current_user.favourites.build) do |f| %>
    <%= hidden_field_tag :micropost_id, micropost.id %>
    <%= f.submit 'Favourite', class: 'btn btn-primary btn-xs' %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Microposts</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
         </ul>
      </div>
    </div>
  </nav>
</header>          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta chaeset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 

    <title>Microposts</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_microposts.html.erb
<ul class="media-list">
  <% microposts.each do |micropost| %>
    <% user = micropost.user %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded"
             src="<%= gravatar_url(micropost.user, options = { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to user.name, user_path(user) %> 
          <span class="text-muted">
            posted at <%= micropost.created_at %>
          </span>
        </div>
        <div>
          <p><%= micropost.content %></p>
        </div>
        <div>
          <% if current_user == micropost.user %>
            <%= link_to "Delete", micropost, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
          <% end %>
          <% if logged_in?%>
            <%= render 'favourites/favourite_button', micropost: micropost, user: current_user %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate microposts %>
</ul>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <%= form_for(@micropost) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-xs-8">
      <ul class="nav nav-tabs nav-justified">
        <li>
          <%= link_to root_path do %>Timelines <span class="badge"></span>
          <%= render 'microposts/microposts', microposts: @microposts %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
    <br>
    <div class="text-center">
       <%= link_to 'Login', login_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>
  

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/favouriteposts.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li>
        <%= link_to root_path do %>Timelines <span class="badge"></span>
        <%= render 'microposts/microposts', microposts: @microposts, user: @user %>
        <% end %>
      </li>
      <li>
        <%= link_to favoriteposts_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span>
        <%= render 'microposts/microposts', microposts: @favoriteposts %>
        <% end %>
      </li>
    </ul>
    <%= render 'microposts/microposts', microposts: @microposts, user: @user %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>


      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive"
             src="<%= gravatar_url(@user, { size: 500 }) %>"
             alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %> Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings<span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers<span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
    <%= render 'microposts/microposts', microposts: @microposts %>
  </div>
</div>